#!/bin/sh

alias ls='ls --color=auto'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# confirm before overwriting something
alias cp="cp -v"
alias mv='mv -v'
alias rm='rm -v'

# Neovim with app-image
alias vim="$HOME"/nvim-appimage/nvim.appimage

# Colorls
alias lc="colorls -1A --sd"

# pipenv
alias p="pipenv"
alias ps="pipenv shell"
alias pi="pipenv install"

# Python
alias py="python"
# Django
alias drun="python manage.py runserver"
alias dmake="python manage.py makemigrations"
alias dmi="python manage.py migrate"
alias dtest="python manage.py test"


# Services
alias spst="sudo service postgresql start"