#!/bin/sh

HISTFILE="$HOME"/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory

PATH="$PATH:$HOME/.local/bin:/usr/bin:/usr/local/bin"
export PATH
export MANWIDTH=999

# NodeVersionManager(NVM)
source ~/.nvm/nvm.sh

# PyEnv Setup
#export PYENV_ROOT="$HOME/.pyenv"
#command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init -)"

#######
# NVM #
#######
#export NVM_DIR="$HOME/.nvm"
## load nvm
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
## load nvm bash_completion
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"