#!/bin/sh

## autoload vcs and colors
autoload -Uz vcs_info
autoload -U colors && colors

precmd() { vcs_info }

# enable only git 
zstyle ':vcs_info:*' enable git 

setopt PROMPT_SUBST

# add a function to check for untracked files in the directory.
# from https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
# 
+vi-git-untracked(){
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        hook_com[staged]+='*' # signify new files with a star
    fi
}

zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:git:*' formats " %{$fg[blue]%}(%{$fg[red]%}%m%u%c%{$fg[yellow]%}%{$fg[magenta]%} %b%{$fg[blue]%})"

# prompt elements
TIME="${prompt_newline}%F{green}(%*)%f"
WOR_DIR="%F{blue}%1~%f"
GIT="$vcs_info_msg_0_ "
PROMPT_SYMBOL="${prompt_newline}%F{white}-> %f"
V_ENV="%F{yellow}(`basename \"$VIRTUAL_ENV\"`)%f"
PROMPT="${TIME} ${V_ENV} ${WOR_DIR} ${GIT} ${PROMPT_SYMBOL}"
