#!/bin/sh

alias ls='lsd -a --group-directories-first'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias reload="source ~/.zshrc"
alias vim="nvim"


#          ╭──────────────────────────────────────────────────────────╮
#          │           confirm before overwriting something           │
#          ╰──────────────────────────────────────────────────────────╯
alias cp="cp -v"
alias mv='mv -v'
alias rm='rm -v'


#          ╭──────────────────────────────────────────────────────────╮
#          │                         Colorls                          │
#          ╰──────────────────────────────────────────────────────────╯
alias lc="colorls -1A --sd"
alias lt="colorls -A --sd --tree=3"


#          ╭──────────────────────────────────────────────────────────╮
#          │                          pipenv                          │
#          ╰──────────────────────────────────────────────────────────╯
alias p="pipenv"
alias ps="pipenv shell"
alias pi="pipenv install"


#          ╭──────────────────────────────────────────────────────────╮
#          │                          Python                          │
#          ╰──────────────────────────────────────────────────────────╯
alias py="python"


#          ╭──────────────────────────────────────────────────────────╮
#          │                          Django                          │
#          ╰──────────────────────────────────────────────────────────╯
alias drun="python manage.py runserver"
alias dmake="python manage.py makemigrations"
alias dmi="python manage.py migrate"
alias dtest="python manage.py test"


#          ╭──────────────────────────────────────────────────────────╮
#          │                         Services                         │
#          ╰──────────────────────────────────────────────────────────╯
alias spst="sudo service postgresql start"


#          ╭──────────────────────────────────────────────────────────╮
#          │                      clear command                       │
#          ╰──────────────────────────────────────────────────────────╯
alias cl="clear"
alias lg='lazygit'


#          ╭──────────────────────────────────────────────────────────╮
#          │         Conditionally add alias to enter chroot          │
#          ╰──────────────────────────────────────────────────────────╯
alias ubuntu="su -c 'exec /data/data/com.termux/files/home/chroot/start_ubuntu.sh'"
alias ubuntu-root="su -c 'exec /data/data/com.termux/files/home/chroot/root_ubuntu.sh'"
alias ubuntu-stop="su -c 'exec /data/data/com.termux/files/home/chroot/stop_ubuntu.sh'"
