
# Completely unbind the old prefix key
unbind C-b
set -g prefix None

# Instantly trigger actions by holding Alt (M-) + Key
bind -n M-c new-window                      # Alt + c = New Window
bind -n M-x confirm-before -p "kill-pane #P? (y/n)" kill-pane # Alt + x = Close Pane
bind -n M-z resize-pane -Z                  # Alt + z = Zoom Pane
bind -n M-d detach-client                   # Alt + d = Detach Session

# Change split windows to Alt + Split Character
bind -n M-| split-window -h -c "#{pane_current_path}"
bind -n M-\ split-window -v -c "#{pane_current_path}"

# Navigate split panes by holding Alt + Arrow Keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# --- RESIZE PANES INSTANTLY WITH ALT + VIM KEYS ---
bind -n -r M-K resize-pane -U 5      # Hold Alt + Shift + K to grow up
bind -n -r M-J resize-pane -D 5      # Hold Alt + Shift + J to grow down
bind -n -r M-H resize-pane -L 5      # Hold Alt + Shift + H to grow left
bind -n -r M-L resize-pane -R 5      # Hold Alt + Shift + L to grow right

# --- QUICK CONFIG RELOAD ---
bind -n M-r source-file ~/.tmux.conf \; display "Config reloaded!"

# Eliminate the legacy Alt/Escape input lag 
set -s escape-time 0

# Disable scrolling through command history
set-option -g mouse on
